language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script: PYTHONPATH=. py.test -v

after_success:  
  - coveralls 
